### ISSUE TITLE
The tool does not create comments from Spotbugs reports

### ISSUE THREAD

**Issue by mak-42** [tomasbjerre/violation-comments-to-gitlab-command-line#12]
The tool does not create comments from Spotbugs reports.
It writes something about wrong line number in debug info:

```
INFO Spotbugs INFO PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS <removed>/CurrentSupplierContactResolverImpl.java 92 <removed>.CurrentSupplierContactResolverImpl
INFO 7 - Sending client request on thread main
7 > POST https://gitlab.<removed>/api/v4/projects/5021/merge_requests/14/discussions
7 > Accept: application/json
7 > Content-Type: application/x-www-form-urlencoded
7 > PRIVATE-TOKEN: ********

INFO 7 - Received server response on thread main
7 < 400
7 < Cache-Control: no-cache
7 < Connection: keep-alive
7 < Content-Length: 102
7 < Content-Type: application/json
7 < Date: Thu, 29 Feb 2024 15:31:31 GMT
7 < Server: nginx
7 < Vary: Origin
7 < X-Content-Type-Options: nosniff
7 < X-Frame-Options: SAMEORIGIN
7 < X-Gitlab-Meta: {"correlation_id":"01HQTQVYF3MC4R2ECGF502EKEM","version":"1"}
7 < X-Request-Id: 01HQTQVYF3MC4R2ECGF502EKEM
7 < X-Runtime: 0.197614

SEVERE Could not create diff discussion!
ProjectID: 5021
SourceSha: e93e0578d3cbc6592874e4944172a9ffb462f7eb
HeadSha: 11adc42fd28679800c4ce273a12917c55161c557
TargetSha: e93e0578d3cbc6592874e4944172a9ffb462f7eb
Path <removed>/CurrentSupplierContactResolverImpl.java
Violation: **Reporter**: Spotbugs


**Rule**: PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS

**Severity**: INFO

**File**: <removed>/CurrentSupplierContactResolverImpl.java L92


**Source**: <removed>.CurrentSupplierContactResolverImpl


PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS
*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-459267307>*
NewLine 92, OldLine92
org.gitlab4j.api.GitLabApiException: 400 Bad request - Note {:line_code=>["can't be blank", "must be a valid line code"]}
	at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:633)
	at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:286)
	at org.gitlab4j.api.DiscussionsApi.createMergeRequestDiscussion(DiscussionsApi.java:332)
	at shadow.se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.createSingleFileComment(GitLabCommentsProvider.java:267)
	at shadow.se.bjurr.violations.comments.lib.CommentsCreator.createSingleFileComments(CommentsCreator.java:163)
	at shadow.se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:85)
	at shadow.se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:40)
	at shadow.se.bjurr.violations.comments.gitlab.lib.ViolationCommentsToGitLabApi.toPullRequest(ViolationCommentsToGitLabApi.java:192)
	at se.bjurr.violations.main.Runner.main(Runner.java:276)
	at se.bjurr.violations.main.Main.main(Main.java:6)

INFO Spotbugs INFO WEM_WEAK_EXCEPTION_MESSAGING <removed>/FacadeReadOnlyHandler.java 255 <removed>.FacadeReadOnlyHandler
INFO 8 - Sending client request on thread main
8 > POST https://gitlab.<removed>/api/v4/projects/5021/merge_requests/14/discussions
8 > Accept: application/json
8 > Content-Type: application/x-www-form-urlencoded
8 > PRIVATE-TOKEN: ********

INFO 8 - Received server response on thread main
8 < 400
8 < Cache-Control: no-cache
8 < Connection: keep-alive
8 < Content-Length: 102
8 < Content-Type: application/json
8 < Date: Thu, 29 Feb 2024 15:31:31 GMT
8 < Server: nginx
8 < Vary: Origin
8 < X-Content-Type-Options: nosniff
8 < X-Frame-Options: SAMEORIGIN
8 < X-Gitlab-Meta: {"correlation_id":"01HQTQVYRTKFH2JMJDQ7C01YMZ","version":"1"}
8 < X-Request-Id: 01HQTQVYRTKFH2JMJDQ7C01YMZ
8 < X-Runtime: 0.345595

SEVERE Could not create diff discussion!
ProjectID: 5021
SourceSha: e93e0578d3cbc6592874e4944172a9ffb462f7eb
HeadSha: 11adc42fd28679800c4ce273a12917c55161c557
TargetSha: e93e0578d3cbc6592874e4944172a9ffb462f7eb
Path <removed>/FacadeReadOnlyHandler.java
Violation: **Reporter**: Spotbugs


**Rule**: WEM_WEAK_EXCEPTION_MESSAGING

**Severity**: INFO

**File**: <removed>/FacadeReadOnlyHandler.java L255


**Source**: <removed>.FacadeReadOnlyHandler


WEM_WEAK_EXCEPTION_MESSAGING
*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a444820957>*
NewLine 255, OldLine255
org.gitlab4j.api.GitLabApiException: 400 Bad request - Note {:line_code=>["can't be blank", "must be a valid line code"]}
	at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:633)
	at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:286)
	at org.gitlab4j.api.DiscussionsApi.createMergeRequestDiscussion(DiscussionsApi.java:332)
	at shadow.se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.createSingleFileComment(GitLabCommentsProvider.java:267)
	at shadow.se.bjurr.violations.comments.lib.CommentsCreator.createSingleFileComments(CommentsCreator.java:163)
	at shadow.se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:85)
	at shadow.se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:40)
	at shadow.se.bjurr.violations.comments.gitlab.lib.ViolationCommentsToGitLabApi.toPullRequest(ViolationCommentsToGitLabApi.java:192)
	at se.bjurr.violations.main.Runner.main(Runner.java:276)
	at se.bjurr.violations.main.Main.main(Main.java:6)

INFO Spotbugs INFO BL_BURYING_LOGIC <removed>/FacadeReadOnlyHandler.java 169 <removed>.FacadeReadOnlyHandler
INFO 9 - Sending client request on thread main
9 > POST https://gitlab.<removed>/api/v4/projects/5021/merge_requests/14/discussions
9 > Accept: application/json
9 > Content-Type: application/x-www-form-urlencoded
9 > PRIVATE-TOKEN: ********

INFO 9 - Received server response on thread main
9 < 400
9 < Cache-Control: no-cache
9 < Connection: keep-alive
9 < Content-Length: 102
9 < Content-Type: application/json
9 < Date: Thu, 29 Feb 2024 15:31:32 GMT
9 < Server: nginx
9 < Vary: Origin
9 < X-Content-Type-Options: nosniff
9 < X-Frame-Options: SAMEORIGIN
9 < X-Gitlab-Meta: {"correlation_id":"01HQTQVZ6GEV251XMQNPWX88AK","version":"1"}
9 < X-Request-Id: 01HQTQVZ6GEV251XMQNPWX88AK
9 < X-Runtime: 0.240770

SEVERE Could not create diff discussion!
ProjectID: 5021
SourceSha: e93e0578d3cbc6592874e4944172a9ffb462f7eb
HeadSha: 11adc42fd28679800c4ce273a12917c55161c557
TargetSha: e93e0578d3cbc6592874e4944172a9ffb462f7eb
Path <removed>/FacadeReadOnlyHandler.java
Violation: **Reporter**: Spotbugs


**Rule**: BL_BURYING_LOGIC

**Severity**: INFO

**File**: <removed>/FacadeReadOnlyHandler.java L169


**Source**: <removed>.FacadeReadOnlyHandler


BL_BURYING_LOGIC
*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a409034818>*
NewLine 169, OldLine169
org.gitlab4j.api.GitLabApiException: 400 Bad request - Note {:line_code=>["can't be blank", "must be a valid line code"]}
	at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:633)
	at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:286)
	at org.gitlab4j.api.DiscussionsApi.createMergeRequestDiscussion(DiscussionsApi.java:332)
	at shadow.se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.createSingleFileComment(GitLabCommentsProvider.java:267)
	at shadow.se.bjurr.violations.comments.lib.CommentsCreator.createSingleFileComments(CommentsCreator.java:163)
	at shadow.se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:85)
	at shadow.se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:40)
	at shadow.se.bjurr.violations.comments.gitlab.lib.ViolationCommentsToGitLabApi.toPullRequest(ViolationCommentsToGitLabApi.java:192)
	at se.bjurr.violations.main.Runner.main(Runner.java:276)
	at se.bjurr.violations.main.Main.main(Main.java:6)
```

The source report:
```xml
<?xml version="1.0" encoding="utf-8"?>
<BugCollection sequence='0' release='' analysisTimestamp='1709220144390' version='4.7.3' timestamp='1709220142489'>
	<Project projectName='...removed...'>
	<!-- removed -->
	</Project>
	<BugInstance instanceOccurrenceNum='0' instanceHash='10de60b621c808014919f7329b0423fd' rank='20' abbrev='PRMC' category='PERFORMANCE' priority='3' type='PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS' instanceOccurrenceMax='0'>
		<ShortMessage>Method appears to call the same method on the same object redundantly</ShortMessage>
		<LongMessage>Method removed.CurrentSupplierContactResolverImpl.resolveContact(removed) appears to call the same method on the same object redundantly</LongMessage>
		<Class classname='removed.CurrentSupplierContactResolverImpl' primary='true'>
			<SourceLine classname='removed.CurrentSupplierContactResolverImpl' start='51' end='93' sourcepath='removed/CurrentSupplierContactResolverImpl.java' sourcefile='CurrentSupplierContactResolverImpl.java'>
				<Message>At CurrentSupplierContactResolverImpl.java:[lines 51-93]</Message>
			</SourceLine>
			<Message>In class removed.CurrentSupplierContactResolverImpl</Message>
		</Class>
		<Method isStatic='false' classname='removed.CurrentSupplierContactResolverImpl' signature='(Lremoved;)Ljava/util/Optional;' name='resolveContact' primary='true'>
			<SourceLine endBytecode='228' classname='removed.CurrentSupplierContactResolverImpl' start='86' end='89' sourcepath='removed/CurrentSupplierContactResolverImpl.java' sourcefile='CurrentSupplierContactResolverImpl.java' startBytecode='0'/>
			<Message>In method removed.CurrentSupplierContactResolverImpl.resolveContact(removed)</Message>
		</Method>
		<SourceLine endBytecode='76' classname='removed.CurrentSupplierContactResolverImpl' start='92' end='92' sourcepath='removed/CurrentSupplierContactResolverImpl.java' sourcefile='CurrentSupplierContactResolverImpl.java' startBytecode='76' primary='true'>
			<Message>At CurrentSupplierContactResolverImpl.java:[line 92]</Message>
		</SourceLine>
		<String value='requireNonNull(Ljava/lang/Object;)Ljava/lang/Object;'>
			<Message>Value requireNonNull(Ljava/lang/Object;)Ljava/lang/Object;</Message>
		</String>
	</BugInstance>
	<BugInstance instanceOccurrenceNum='0' instanceHash='b5d4dbb0bb23d74cd078dffa6061bd08' rank='20' abbrev='BL' category='STYLE' priority='3' type='BL_BURYING_LOGIC' instanceOccurrenceMax='0'>
		<ShortMessage>Method buries logic to the right (indented) more than it needs to be</ShortMessage>
		<LongMessage>Method removed.FacadeReadOnlyHandler.lambda$resolveDefaultValue$3(Field, XFWDefaultValue) buries logic to the right (indented) more than it needs to be</LongMessage>
		<Class classname='removed.FacadeReadOnlyHandler' primary='true'>
			<SourceLine classname='removed.FacadeReadOnlyHandler' start='52' end='257' sourcepath='removed/FacadeReadOnlyHandler.java' sourcefile='FacadeReadOnlyHandler.java'>
				<Message>At FacadeReadOnlyHandler.java:[lines 52-257]</Message>
			</SourceLine>
			<Message>In class removed.FacadeReadOnlyHandler</Message>
		</Class>
		<Method isStatic='true' classname='removed.FacadeReadOnlyHandler' signature='(removed;)Ljava/lang/Object;' name='lambda$resolveDefaultValue$3' primary='true'>
			<SourceLine endBytecode='289' classname='removed.FacadeReadOnlyHandler' start='161' end='175' sourcepath='removed/FacadeReadOnlyHandler.java' sourcefile='FacadeReadOnlyHandler.java' startBytecode='0'/>
			<Message>In method removed.FacadeReadOnlyHandler.lambda$resolveDefaultValue$3(Field, XFWDefaultValue)</Message>
		</Method>
		<SourceLine endBytecode='94' classname='removed.FacadeReadOnlyHandler' start='169' end='175' sourcepath='removed/FacadeReadOnlyHandler.java' sourcefile='FacadeReadOnlyHandler.java' startBytecode='54' primary='true'>
			<Message>At FacadeReadOnlyHandler.java:[lines 169-175]</Message>
		</SourceLine>
	</BugInstance>
	<BugInstance instanceOccurrenceNum='0' instanceHash='14de8676a94401345776c69445d4c523' rank='20' abbrev='WEM' category='STYLE' priority='3' type='WEM_WEAK_EXCEPTION_MESSAGING' instanceOccurrenceMax='0'>
		<ShortMessage>Method throws exception with static message string</ShortMessage>
		<LongMessage>Method removed.FacadeReadOnlyHandler.checkFacadeReadOnly(BeforeStoreEvent) throws exception with static message string</LongMessage>
		<Class classname='removed.FacadeReadOnlyHandler' primary='true'>
			<SourceLine classname='removed.FacadeReadOnlyHandler' start='52' end='257' sourcepath='removed/FacadeReadOnlyHandler.java' sourcefile='FacadeReadOnlyHandler.java'>
				<Message>At FacadeReadOnlyHandler.java:[lines 52-257]</Message>
			</SourceLine>
			<Message>In class removed.FacadeReadOnlyHandler</Message>
		</Class>
		<Method isStatic='false' classname='removed.FacadeReadOnlyHandler' signature='(Lremoved;)V' name='checkFacadeReadOnly' primary='true'>
			<SourceLine endBytecode='284' classname='removed.FacadeReadOnlyHandler' start='225' end='257' sourcepath='removed/FacadeReadOnlyHandler.java' sourcefile='FacadeReadOnlyHandler.java' startBytecode='0'/>
			<Message>In method removed.FacadeReadOnlyHandler.checkFacadeReadOnly(BeforeStoreEvent)</Message>
		</Method>
		<SourceLine endBytecode='114' classname='removed.FacadeReadOnlyHandler' start='255' end='255' sourcepath='removed/FacadeReadOnlyHandler.java' sourcefile='FacadeReadOnlyHandler.java' startBytecode='114' primary='true'>
			<Message>At FacadeReadOnlyHandler.java:[line 255]</Message>
		</SourceLine>
	</BugInstance>
	<BugCategory category='PERFORMANCE'>
		<Description>Performance</Description>
	</BugCategory>
	<BugCategory category='STYLE'>
		<Description>Dodgy code</Description>
	</BugCategory>
	<BugPattern abbrev='BL' category='STYLE' type='BL_BURYING_LOGIC'>
		<ShortDescription>Method buries logic to the right (indented) more than it needs to be</ShortDescription>
		<Details>
    		
    		&lt;p&gt;Looks for relatively large &lt;code&gt;if&lt;/code&gt; blocks of code, where you unconditionally return from them,
    		and then follow that with an unconditional return of a small block. This places the bulk of the logic to the right indentation-wise,
    		making it more difficult to read than needed. It would be better to invert the logic of the if block, and immediately return,
    		allowing the bulk of the logic to be move to the left for easier reading.&lt;/p&gt;
    		
    	</Details>
	</BugPattern>
	<BugPattern abbrev='WEM' category='STYLE' type='WEM_WEAK_EXCEPTION_MESSAGING'>
		<ShortDescription>Method throws exception with static message string</ShortDescription>
		<Details>
			
			&lt;p&gt;This method creates and throws an exception using a static string as the exceptions message.
			Without any specific context of this particular exception invocation, such as the values of parameters,
			key member variables, or local variables, it may be difficult to infer how this exception occurred. Consider
			adding context to the exception message.&lt;/p&gt;
			
		</Details>
	</BugPattern>
	<BugPattern abbrev='PRMC' category='PERFORMANCE' type='PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS'>
		<ShortDescription>Method appears to call the same method on the same object redundantly</ShortDescription>
		<Details>
			
			&lt;p&gt;This method makes two consecutive calls to the same method, using the same constant
			parameters, on the same instance, without any intervening changes to the objects. If this
			method does not make changes to the object, which it appears it doesn't, then making
			two calls is just a waste. These method calls could be combined by assigning the
			result into a temporary variable, and using the variable the second time.&lt;/p&gt;
			
		</Details>
	</BugPattern>
	<BugCode abbrev='BL'>
		<Description>Burying Logic</Description>
	</BugCode>
	<BugCode abbrev='PRMC'>
		<Description>Possibly Redundant Method Calls</Description>
	</BugCode>
	<BugCode abbrev='WEM'>
		<Description>Weak Exception Messaging</Description>
	</BugCode>
	<Errors missingClasses='0' errors='0'/>
	<FindBugsSummary num_packages='12' total_classes='44' priority_3='3' total_size='562' clock_seconds='4.94' referenced_classes='236' vm_version='11.0.18+10-LTS' total_bugs='3' java_version='11.0.18' gc_seconds='0.07' alloc_mbytes='512.00' cpu_seconds='20.33' peak_mbytes='330.08' timestamp='Thu, 29 Feb 2024 18:22:22 +0300'>
		<!-- removed -->
		<FileStats path='removed/CurrentSupplierContactResolverImpl.java' size='33' bugHash='74de4b14bd706c44609852a94e782b11' bugCount='1'/>
		<!-- removed -->
		<FileStats path='removed/FacadeReadOnlyHandler.java' size='114' bugHash='b23f50b2f2f345cdcdc70fc36acea15e' bugCount='2'/>
		<!-- removed -->
		<PackageStats package='removed' total_bugs='1' priority_3='1' total_size='149' total_types='6'>
			<!-- removed -->
			<ClassStats bugs='1' size='33' priority_3='1' interface='false' sourceFile='CurrentSupplierContactResolverImpl.java' class='removed.CurrentSupplierContactResolverImpl'/>
			<!-- removed -->
		</PackageStats>
		<!-- removed -->
		<PackageStats package='removed' total_bugs='2' priority_3='2' total_size='115' total_types='3'>
			<ClassStats bugs='2' size='98' priority_3='2' interface='false' sourceFile='FacadeReadOnlyHandler.java' class='removed.FacadeReadOnlyHandler'/>
			<!-- removed -->
		</PackageStats>
		<!-- removed -->
		<FindBugsProfile>
			<!-- removed -->
		</FindBugsProfile>
	</FindBugsSummary>
	<ClassFeatures/>
	<History/>
</BugCollection>
```

I merged branches before build the project like it was recommended in readme.

The problem like this occurs only while processing Spotbugs reports. The tool creates comments while processing Checkstyle reports.

**Comment by mak-42** [comment]
> You may want to try this alternative solution: https://github.com/tomasbjerre/violations-command-line?tab=readme-ov-file#gitlab

Thanks, i've already used it. This tool looks more friendly and it will be great if you can fix the problem.

**Comment by tomasbjerre** [comment]
i updated the client now and released `1.32.2`. Does it work better?

**Comment by tomasbjerre** [comment]
I'm updating the logging a bit and releasing `1.33.0`. The wrong value is logged for `OldLine`: https://github.com/tomasbjerre/violation-comments-to-gitlab-lib/blob/36cdd31ecef03923facba71a9f1dfafb1d444b60/src/main/java/se/bjurr/violations/comments/gitlab/lib/GitLabCommentsProvider.java#L300

Also found this issue:
https://stackoverflow.com/questions/65926187/what-is-a-gitlab-line-code-as-referenced-when-creating-a-new-merge-request-threa

Not sure if this can be solved or you may have to set `-cocc true`. Or maby create comments with `-create-comment-with-all-single-file-comments` to avoid commenting on the diff.

I often end up just creating the one big comment because developers don't want all emails generated from the commenting. And I combine that with using the [violations-maven-plugin](https://github.com/tomasbjerre/violations-maven-plugin) or [violations-gradle-plugin](https://github.com/tomasbjerre/violations-gradle-plugin) to have the build fail with a clear error in the build log.

**Comment by tomasbjerre** [comment]
This is Claude (Anthropic's AI assistant), commenting here while helping Tomas triage open issues — not Tomas himself.

Looking at the history: the `OldLine` logging fix and workaround suggestions (`-cocc true`, or `-create-comment-with-all-single-file-comments` to avoid per-line diff comments) went out in v1.33.0 back in March 2024, but there's been no follow-up confirming whether that resolved the GitLab 400 errors.

Closing for now since it's been quiet for a long while. If you're still seeing this with a current version, please reopen (or file a new issue) with fresh logs and we'll take another look.
