### ISSUE TITLE
Versions 1.8.0+ from NPM are not working

### ISSUE THREAD

**Issue by riomus** [tomasbjerre/violation-comments-to-gitlab-command-line#2]
After installing any version 1.8+ from NPM, any execution results in exception:

Exception in thread "main" java.lang.IllegalArgumentException: -comment-only-changed-files was not found in this result at all. Did you perhaps forget to add it to withArguments(...)?
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:119)
	at shadow.se.softhouse.jargo.ParsedArguments.get(ParsedArguments.java:75)
	at se.bjurr.violations.main.Runner.main(Runner.java:158)
	at se.bjurr.violations.main.Main.main(Main.java:6)

Java: 11
Linux

**Comment by tomasbjerre** [comment]
Should be fixed now in 1.13.0

**Comment by riomus** [comment]
can confirm that now it is working as expected, awesome, thx
