### ISSUE TITLE
Unable to create comments

### ISSUE THREAD

**Issue by riomus** [tomasbjerre/violation-comments-to-gitlab-command-line#3]
Unfortunately, when calling GitLab in order to create a comment, I get an issue:

```

INFO Asking GitLabCommentsProvider to comment:
INFO Scapegoat WARN com.sksamuel.scapegoat.inspections.inference.ProductWithSerializableInferred authentication/service/src/main/scala/ai/iambot/authentication/jobs/AuthTokenCleaner.scala 29 
INFO 1 * Sending client request on thread main
1 > POST https://gitlab.com/api/v4/projects/11222782/merge_requests/493/discussions
1 > Accept: application/json
1 > Content-Type: application/x-www-form-urlencoded
1 > PRIVATE-TOKEN: HIDDEN
body=**Reporter**%3A+Scapegoat%0A%0A**Rule**%3A+com.sksamuel.scapegoat.inspections.inference.ProductWithSerializableInferred%0A%0A**Severity**%3A+WARN%0A%0A**File**%3A+%2Fhome%2Friomus%2Fgit%2Fiambot-data-manager%2Fauthentication%2Fservice%2Fsrc%2Fmain%2Fscala%2Fai%2Fiambot%2Fauthentication%2Fjobs%2FAuthTokenCleaner.scala+L29%0A%0A%0AProduct+with+Serializable+inferred%0A%0A%0A*%3Cthis+is+a+auto+generated+comment+from+violation-comments-lib+F7F8ASD8123FSDF%3E*+*%3Ca-1484022715%3E*&position%5Bbase_sha%5D=fd1b2debce7da2130ccbc2a852e183eb94adf447&position%5Bstart_sha%5D=36c547054c4ee2edfa11f88d460ee1329672e5f9&position%5Bhead_sha%5D=ee4779446400ef2c7ae32e6c546e03091cfd67c6&position%5Bposition_type%5D=text&position%5Bnew_path%5D=authentication%2Fservice%2Fsrc%2Fmain%2Fscala%2Fai%2Fiambot%2Fauthentication%2Fjobs%2FAuthTokenCleaner.scala&position%5Bnew_line%5D=29&position%5Bold_path%5D=authentication%2Fservice%2Fsrc%2Fmain%2Fscala%2Fai%2Fiambot%2Fauthentication%2Fjobs%2FAuthTokenCleaner.scala

INFO 1 * Client response received on thread main
1 < 400
1 < Cache-Control: no-cache
1 < Content-Length: 121
1 < Content-Type: application/json
1 < Date: Sun, 15 Mar 2020 13:02:08 GMT
1 < GitLab-LB: fe-23-lb-gprd
1 < GitLab-SV: localhost
1 < RateLimit-Limit: 600
1 < RateLimit-Observed: 4
1 < RateLimit-Remaining: 596
1 < RateLimit-Reset: 1584277388
1 < RateLimit-ResetTime: Sun, 15 Mar 2020 13:03:08 GMT
1 < Server: nginx
1 < Vary: Origin
1 < X-Content-Type-Options: nosniff
1 < X-Frame-Options: SAMEORIGIN
1 < X-Request-Id: 8aHLLMchoa3
1 < X-Runtime: 0.159464
{"message":"400 (Bad request) \"Note {:line_code=\u003e[\"can't be blank\", \"must be a valid line code\"]}\" not given"}

SEVERE Could not create diff discussion!
ProjectID: 11222782
SourceSha: fd1b2debce7da2130ccbc2a852e183eb94adf447
HeadSha: ee4779446400ef2c7ae32e6c546e03091cfd67c6
TargetSha: 36c547054c4ee2edfa11f88d460ee1329672e5f9
Path authentication/service/src/main/scala/ai/iambot/authentication/jobs/AuthTokenCleaner.scala
Violation: **Reporter**: Scapegoat

**Rule**: com.sksamuel.scapegoat.inspections.inference.ProductWithSerializableInferred

**Severity**: WARN

**File**: /home/riomus/git/iambot-data-manager/authentication/service/src/main/scala/ai/iambot/authentication/jobs/AuthTokenCleaner.scala L29


Product with Serializable inferred


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1484022715>*
NewLine 29, OldLine29
org.gitlab4j.api.GitLabApiException: 400 (Bad request) "Note {:line_code=>["can't be blank", "must be a valid line code"]}" not given
	at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:593)
	at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:264)
	at org.gitlab4j.api.DiscussionsApi.createMergeRequestDiscussion(DiscussionsApi.java:332)
	at shadow.se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.createSingleFileComment(GitLabCommentsProvider.java:185)
	at shadow.se.bjurr.violations.comments.lib.CommentsCreator.createSingleFileComments(CommentsCreator.java:147)
	at shadow.se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:71)
	at shadow.se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:38)
	at shadow.se.bjurr.violations.comments.gitlab.lib.ViolationCommentsToGitLabApi.toPullRequest(ViolationCommentsToGitLabApi.java:175)
	at se.bjurr.violations.main.Runner.main(Runner.java:255)
	at se.bjurr.violations.main.Main.main(Main.java:6)

```

We are using cloud gitlab (gitlab.com)

**Comment by riomus** [comment]
What is more, I can see that as configured, MR name was updated, as I have configured, only the comments are not working properly

**Comment by tomasbjerre** [comment]
Judging from the stacktrace it looks like you have an old version of the tool.

Did you perform the merge before performing the analysis?

**Comment by riomus** [comment]
I am using the latest version (1.13.0)

I am executing the tool ina merge request context on the CI (or localy on the branch). In both situations, I have same problem.

**Comment by tomasbjerre** [comment]
If you don't merge source branch into target branch before doing the analysis, the tools will create report files with line numbers that does not match the diff in the merge request.

**Comment by riomus** [comment]
Ok, I have made merge before making the merge, and still, have same error

**Comment by riomus** [comment]
I think that one of the solutions would be adding the ability to create general notes, instead of commenting on the exact line (a behaviour that can be turned on using some flag)

**Comment by tomasbjerre** [comment]
Did you try `-create-comment-with-all-single-file-comments` ?

I think the problem here is that the issue reported by the analysis is reported on a line that is on the edge of the diff.

This error should not block other comments from being added. Comments that are clearly within the diff

**Comment by riomus** [comment]
Using a combination of flags: -ccwasfc true -csfc false , creates general notes in MR. Now I will just test it from our CI, but it looks good so far.

**Comment by riomus** [comment]
I think that we can close the issue, it looks like using that configuration I am able to create comments for MRs (but not in proper lines, just for whole MR)
